from .identical_compressor import IdenticalCompressor
from .qsgd_compressor import QSGDCompressor
from .hyper_sphere_compressor import HyperSphereCompressor
from .nearest_neighbor_compressor import NearestNeighborCompressor
from .residual_compressor import ResidualCompressor
from .signsgd_compressor import SignSGDCompressor