from .base_quantizer import BaseQuantizer
from .sgd_quantizer import SGDQuantizer
from .qsgd_quantizer import QSGDQuantizer
from .hyper_sphere_quantizer import HyperSphereQuantizer
from .nearest_neighbor_quantizer import NearestNeighborQuantizer
from .residual_quantizer import ResidualQuantizer